In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [3]:
arr.dtype

dtype('int32')

In [4]:
arr = np.array([1, 2, 3], dtype=np.float32)
arr.dtype

dtype('float32')

In [5]:
arr = np.array([[1, 2, 3], [1, 2, 3]], dtype=np.uint8)
arr.dtype

dtype('uint8')

In [6]:
arr.shape

(2, 3)

# Shape

In [7]:
arr.reshape(6)

array([1, 2, 3, 1, 2, 3], dtype=uint8)

In [8]:
arr.reshape(-1)

array([1, 2, 3, 1, 2, 3], dtype=uint8)

In [9]:
arr.reshape(3, -1)

array([[1, 2],
       [3, 1],
       [2, 3]], dtype=uint8)

In [10]:
new_arr = arr.reshape(-1)
new_arr.shape

(6,)

In [11]:
arr

array([[1, 2, 3],
       [1, 2, 3]], dtype=uint8)

# Random

In [12]:
arr = np.random.randn(8, 8)

In [13]:
arr.reshape(32, -1).shape

(32, 2)

In [14]:
arr.reshape(4, 8, -1).shape

(4, 8, 2)

In [15]:
arr.ravel().shape

(64,)

In [16]:
arr.ndim

2

In [17]:
len(arr.shape)

2

In [18]:
ex_arr = np.expand_dims(arr, 0)
ex_arr.shape

(1, 8, 8)

In [19]:
np.array([[3]]).shape

(1, 1)

In [20]:
ex_arr = np.expand_dims(ex_arr, -1)
ex_arr.shape

(1, 8, 8, 1)

# Zeros & Ones

In [21]:
zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros(1)

array([0.])

In [23]:
ones = np.ones([10, 5])
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [24]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [26]:
np.array(['a', 'v', 1, 2])

array(['a', 'v', '1', '2'], dtype='<U11')

# index

In [27]:
arr.shape

(8, 8)

In [28]:
arr

array([[-1.51787703e-01,  1.38630395e+00, -1.05002343e+00,
         4.11138024e-01,  3.37490989e-01,  4.60801359e-01,
         3.67695882e-01,  1.15076002e+00],
       [ 1.09511129e+00, -5.27404078e-02,  5.02659479e-02,
         1.74352308e-01, -1.41730550e+00, -1.02653627e-01,
         1.30336759e+00,  5.47435847e-01],
       [-3.73592507e-02, -7.82734042e-01, -2.81135119e-02,
         1.14718050e+00,  1.08125394e+00,  1.27239972e-01,
        -1.28306766e-01, -2.87252744e-01],
       [-1.11765887e+00, -1.60650573e-01,  6.77260691e-01,
        -1.22223583e+00, -1.45960020e+00,  7.43730350e-01,
         1.52288821e-01, -9.18158755e-01],
       [ 1.29748201e-01, -6.40083438e-01,  1.13664716e+00,
         3.61607873e-01, -9.92335359e-01, -6.79192330e-01,
         1.65078428e-01,  7.87123986e-01],
       [-1.18481022e-01, -1.99084288e+00, -5.89080312e-01,
        -1.77532225e+00,  1.64719563e+00,  1.10720802e-01,
        -5.25857190e-01,  1.04413975e-01],
       [-1.99533059e+00,  1.026831

In [29]:
arr[:4, 4:]

array([[ 0.33749099,  0.46080136,  0.36769588,  1.15076002],
       [-1.4173055 , -0.10265363,  1.30336759,  0.54743585],
       [ 1.08125394,  0.12723997, -0.12830677, -0.28725274],
       [-1.4596002 ,  0.74373035,  0.15228882, -0.91815875]])

In [30]:
arr[0, -1]

1.1507600174345425

In [31]:
arr[0][-1]

1.1507600174345425

In [32]:
arr > 0

array([[False,  True, False,  True,  True,  True,  True,  True],
       [ True, False,  True,  True, False, False,  True,  True],
       [False, False, False,  True,  True,  True, False, False],
       [False, False,  True, False, False,  True,  True, False],
       [ True, False,  True,  True, False, False,  True,  True],
       [False, False, False, False,  True,  True, False,  True],
       [False,  True,  True,  True, False,  True,  True, False],
       [ True,  True,  True,  True, False, False,  True, False]])

In [33]:
arr[arr > 0] = 1

In [34]:
arr

array([[-0.1517877 ,  1.        , -1.05002343,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ],
       [ 1.        , -0.05274041,  1.        ,  1.        , -1.4173055 ,
        -0.10265363,  1.        ,  1.        ],
       [-0.03735925, -0.78273404, -0.02811351,  1.        ,  1.        ,
         1.        , -0.12830677, -0.28725274],
       [-1.11765887, -0.16065057,  1.        , -1.22223583, -1.4596002 ,
         1.        ,  1.        , -0.91815875],
       [ 1.        , -0.64008344,  1.        ,  1.        , -0.99233536,
        -0.67919233,  1.        ,  1.        ],
       [-0.11848102, -1.99084288, -0.58908031, -1.77532225,  1.        ,
         1.        , -0.52585719,  1.        ],
       [-1.99533059,  1.        ,  1.        ,  1.        , -2.39645214,
         1.        ,  1.        , -1.08660728],
       [ 1.        ,  1.        ,  1.        ,  1.        , -0.2537091 ,
        -1.49145531,  1.        , -0.9178965 ]])

# Broadcast

In [35]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [38]:
arr + np.array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

# Math

In [39]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [40]:
arr * arr

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [41]:
np.add(arr, arr)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [42]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [43]:
np.sum(arr)

36

In [44]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
arr.shape

(3, 3)

In [46]:
np.sum(arr, axis=0)

array([ 9, 12, 15])

In [47]:
np.max(arr)

8

In [48]:
np.min(arr)

0

In [49]:
np.mean(arr, axis=1)

array([1., 4., 7.])

In [50]:
np.argmax([1, 5, 3, 2, 0, 8, 3])

5

In [51]:
np.unique([2, 4, 6, 3, 4, 3, 6, 4, 4, 2, 1, 8], return_counts=True)

(array([1, 2, 3, 4, 6, 8]), array([1, 2, 2, 4, 2, 1], dtype=int64))

In [52]:
new_arr = arr.copy()

In [53]:
new_arr[arr > 5] = 0

In [54]:
new_arr

array([[0, 1, 2],
       [3, 4, 5],
       [0, 0, 0]])

In [55]:
rand_arr = np.random.randn(3, 3)
rand_arr

array([[ 0.34313304,  2.33458149, -0.47199546],
       [ 0.02683475,  0.84198395, -1.12341987],
       [-1.93028553, -0.11173518, -0.60550856]])

In [56]:
np.dot(arr, rand_arr)

array([[ -3.83373631,   0.61851359,  -2.334437  ],
       [ -8.51468952,   9.81300436,  -8.9372087 ],
       [-13.19564273,  19.00749513, -15.53998039]])

In [57]:
np.where(arr > 5, rand_arr, arr)

array([[ 0.        ,  1.        ,  2.        ],
       [ 3.        ,  4.        ,  5.        ],
       [-1.93028553, -0.11173518, -0.60550856]])

In [58]:
arr > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [59]:
np.where((arr > 3) & (arr < 7), 1, 0)

array([[0, 0, 0],
       [0, 1, 1],
       [1, 0, 0]])

In [60]:
(arr > 3) & (arr < 7)

array([[False, False, False],
       [False,  True,  True],
       [ True, False, False]])

In [61]:
arr.astype(np.uint8)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=uint8)

In [62]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
rand_arr

array([[ 0.34313304,  2.33458149, -0.47199546],
       [ 0.02683475,  0.84198395, -1.12341987],
       [-1.93028553, -0.11173518, -0.60550856]])

In [64]:
arr.shape, rand_arr.shape

((3, 3), (3, 3))

In [65]:
np.concatenate([np.expand_dims(arr, -1), 
                np.expand_dims(rand_arr, -1)], axis=-1).shape

(3, 3, 2)