In [1]:
import numpy as np

# Tensor

딥러닝을 하다보면 Tensor라는 개념이 많이 나올 것이다.  
그 중 Tensor의 개념을 잘 이해하는 것이 중요한데.  
딥러닝에서는 주로 고차원적인 데이터를 많이 사용될 것이기 때문  

Numpy는 그런 고차원적인 데이터를 다루기 쉽게 만들어져 있어 딥러닝을 하시게 된다면 늘 접하게 될 것임  
자세한 Tensor에 대한 내용은 다른 강사님께서 다루어줄 것이고, numpy를 통해 간단하게만 이해하도록 하자

## 0차원

- numpy array는 1 또는 5, 10와 같이 숫자 데이터를 array화 해줄 수 있음

In [3]:
arr = np.array(10)
arr

array(10)

Scalar로 들어갔을 때는 shape가 아무것도 없는 것으로 나온다 

In [5]:
arr.shape

()

## 1차원

- 숫자가 10과 같이 하나만 들어간다고 해도 [] 리스트를 한번 씌우게 되면 차원이 생긴다 
- 이때는 1차원이 되는건데 numpy 에서 shape를 표현 할 때 (1)이 아닌 (1, )  이런 식으로 표현하게 됨 

In [6]:
arr = np.array([10])
arr.shape

(1,)

- 명심해야 할 것이 있는데 위의 (3, )에서 3은 3이라는 값이 들어간 것이 아닌 shape라는 것을 명심  
- 1차원에 3개의 값이 들어갔다는 의미
- 해석하자면 1차원에 3개의 값(value)가 들어감

In [8]:
arr = np.array([1, 2, 3])
arr.shape

(3,)

## 2차원

대문자를 추가적으로 씌우면 차원이 추가적으로 하나 생김

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.shape

(3, 3)

위의 shape를 다시 보자면 차원이 2개가 있고, 각 차원 마다 각각 3개의 값이 들어있다고 생각하면 됨

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

참고로 0차원 숫자에 대문자에 대괄호를 2번 씌우면 두개의 차원이 됨

In [13]:
arr = np.array([[10]])
arr.shape

(1, 1)

## 다 차원

In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr.shape

(2, 3, 3)

In [12]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
arr = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]], [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])
arr.shape

(2, 2, 3, 3)

In [16]:
arr

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [9]:
arr.shape

(2, 2, 3, 3)

In [9]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [10]:
arr * 10

array([10, 20, 30])

In [12]:
arr + 10

array([11, 12, 13])

In [13]:
arr + arr

array([2, 4, 6])

# Numpy 정보

## data type

array의 dtype을 본다. 

In [17]:
arr.dtype

dtype('int32')

.astype()으로 datatype을 변환 가능

In [19]:
arr = arr.astype('float32')
arr.dtype

dtype('float32')

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [21]:
arr.ndim

4

In [22]:
arr.size

36

## Reshape

In [23]:
arr

array([[[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]],


       [[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]]], dtype=float32)

In [24]:
arr.reshape((1, 9))

ValueError: cannot reshape array of size 36 into shape (1,9)

In [25]:
arr.reshape(-1)

array([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8.,
       9., 1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7.,
       8., 9.], dtype=float32)

In [26]:
data = np.random.randn(8, 8)
data.shape

(8, 8)

In [27]:
data_res = data.reshape(32, 2)
data_res.shape

(32, 2)

In [28]:
data_res = data_res.reshape(16, -1)
data_res.shape

(16, 4)

In [29]:
data_res = data_res.reshape(8, 4, -1)
data_res.shape

(8, 4, 2)

## Ravel

In [30]:
arr.shape

(2, 2, 3, 3)

arr의 차원을 1로 바꿔줌  
나중에 배울 layer를 flatten 할 때 같은 기능이라 생각하면 됨 

In [32]:
arr = arr.ravel()
arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8.,
       9., 1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7.,
       8., 9.], dtype=float32)

In [33]:
arr.shape

(36,)

arr.reshape(-1) 와 같음

In [34]:
arr.reshape(-1)

array([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8.,
       9., 1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7.,
       8., 9.], dtype=float32)

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

In [37]:
arr.shape

(36,)

In [39]:
np.expand_dims(arr, -1).shape

(36, 1)

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones([10])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.ones([3, 3]) * 9

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
np.zeros_like(arr)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]])

In [35]:
arr.dtype

dtype('int32')

In [36]:
arr

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [41]:
arr_f = arr.astype(np.float16)
arr_f.dtype

dtype('float16')

In [43]:
np.array([1, 2, 3], dtype=np.float16)

array([1., 2., 3.], dtype=float16)

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
arr_2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [48]:
arr + arr_2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [49]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [51]:
arr + np.array([1, 2, 3])

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

# Index

In [20]:
arr  # [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr[0][1]

2

In [21]:
arr[0, 1]

2

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr.shape

(3, 3)

# Slicing

In [25]:
arr[0]

array([1, 2, 3])

In [26]:
arr[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr[0][1:]

array([2, 3])

In [30]:
arr[0, 1:]

array([2, 3])

## Boolean Indexing

In [33]:
data = np.random.randn(3, 3)
data

array([[ 0.51253973, -0.29723714,  0.72194289],
       [ 0.99150003, -1.78376966, -0.60182466],
       [ 1.3887837 , -1.07356403,  1.32889542]])

In [34]:
data > 0

array([[ True, False,  True],
       [ True, False, False],
       [ True, False,  True]])

In [36]:
data[data > 0]

array([0.51253973, 0.72194289, 0.99150003, 1.3887837 , 1.32889542])

In [37]:
data[data > 0] = 1

In [38]:
data

array([[ 1.        , -0.29723714,  1.        ],
       [ 1.        , -1.78376966, -0.60182466],
       [ 1.        , -1.07356403,  1.        ]])

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [16]:
arr + np.array([10, 12])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## Math Function

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.sum(arr)

45

In [56]:
sum(arr)

array([12, 15, 18])

In [58]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [59]:
np.max(arr)

9

In [60]:
np.min(arr)

1

In [61]:
np.max(arr, axis=1)

array([3, 6, 9])

In [62]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [63]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [64]:
x = 10
y = 40

In [65]:
np.maximum(x, y)

40

In [67]:
np.maximum(arr, np.random.randn(3, 3))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [68]:
np.mean(arr)

5.0

In [69]:
arr.mean()

5.0

In [71]:
np.argmin([8, 4, 6, 3, 7, 0, 6, 4, 8, 5])

5

In [72]:
np.argmax([8, 4, 6, 3, 7, 0, 6, 4, 8, 5])

0

In [74]:
data = np.random.randn(3, 3)
data

array([[ 0.23224845, -0.45460196, -0.07520463],
       [ 0.68726246, -0.27930024, -1.41230492],
       [-0.74933098, -1.33525685, -0.05248074]])

In [75]:
np.argmax(data)

3

In [76]:
data = np.random.randn(3, 3, 3)
np.argmax(data)

23

In [78]:
# np.where()    np.unique()

In [79]:
data

array([[[-1.22823122, -0.29487198,  0.03820292],
        [ 1.65911432, -0.33926299, -0.26105841],
        [-2.32598986, -0.73472773,  1.00787859]],

       [[-0.84565064,  0.12395116, -0.63878074],
        [ 0.0415661 , -0.95534315,  0.66513028],
        [-2.51754303,  1.2526999 ,  0.50516848]],

       [[ 0.72770898,  0.37953243,  0.65723216],
        [ 1.37627515, -0.28939585,  2.8265142 ],
        [ 1.21801742,  0.79844653,  1.10541735]]])

In [84]:
data_w = np.where(data > 0, 5, 0)
data_w

array([[[0, 0, 5],
        [5, 0, 0],
        [0, 0, 5]],

       [[0, 5, 0],
        [5, 0, 5],
        [0, 5, 5]],

       [[5, 5, 5],
        [5, 0, 5],
        [5, 5, 5]]])

In [85]:
np.unique(data_w)

array([0, 5])

In [86]:
np.unique(data_w, return_counts=True)

(array([0, 5]), array([11, 16], dtype=int64))