In [2]:
import numpy as np

In [4]:
arr = np.array(10)
arr.shape

()

In [5]:
arr

array(10)

In [10]:
arr = np.array(1)
arr.shape

()

In [6]:
arr = np.array([10])
arr.shape

(1,)

In [11]:
arr = np.array([1, 2, 3])
arr.shape

(3,)

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.shape, arr

((3, 3), array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
arr.shape, arr

((2, 3, 3), array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]))

In [29]:
arr = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]], [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])
arr.shape, arr

((2, 2, 3, 3), array([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],
 
 
        [[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],
 
         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]]))

In [9]:
arr.shape

(2, 2, 3, 3)

In [9]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [10]:
arr * 10

array([10, 20, 30])

In [12]:
arr + 10

array([11, 12, 13])

In [13]:
arr + arr

array([2, 4, 6])

In [16]:
arr + np.array([10, 12])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [17]:
arr.dtype

dtype('int32')

In [20]:
arr.ndim

1

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones([10])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.ones([3, 3]) * 9

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
np.zeros_like(arr)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]])

In [35]:
arr.dtype

dtype('int32')

In [36]:
arr

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [41]:
arr_f = arr.astype(np.float16)
arr_f.dtype

dtype('float16')

In [43]:
np.array([1, 2, 3], dtype=np.float16)

array([1., 2., 3.], dtype=float16)

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
arr_2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [48]:
arr + arr_2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [49]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [51]:
arr + np.array([1, 2, 3])

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

# Index

In [20]:
arr  # [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr[0][1]

2

In [21]:
arr[0, 1]

2

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr.shape

(3, 3)

# Slicing

In [25]:
arr[0]

array([1, 2, 3])

In [26]:
arr[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr[0][1:]

array([2, 3])

In [30]:
arr[0, 1:]

array([2, 3])

## Boolean Indexing

In [33]:
data = np.random.randn(3, 3)
data

array([[ 0.51253973, -0.29723714,  0.72194289],
       [ 0.99150003, -1.78376966, -0.60182466],
       [ 1.3887837 , -1.07356403,  1.32889542]])

In [34]:
data > 0

array([[ True, False,  True],
       [ True, False, False],
       [ True, False,  True]])

In [36]:
data[data > 0]

array([0.51253973, 0.72194289, 0.99150003, 1.3887837 , 1.32889542])

In [37]:
data[data > 0] = 1

In [38]:
data

array([[ 1.        , -0.29723714,  1.        ],
       [ 1.        , -1.78376966, -0.60182466],
       [ 1.        , -1.07356403,  1.        ]])

## Reshape

In [39]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr.reshape((1, 9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [44]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
data = np.random.randn(8, 8)
data.shape

(8, 8)

In [49]:
data_res = data.reshape(32, 2)
data_res.shape

(32, 2)

In [51]:
data_res = data_res.reshape(16, -1)
data_res.shape

(16, 4)

In [52]:
data_res = data_res.reshape(8, 4, -1)
data_res.shape

(8, 4, 2)

## Math Function

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.sum(arr)

45

In [56]:
sum(arr)

array([12, 15, 18])

In [58]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [59]:
np.max(arr)

9

In [60]:
np.min(arr)

1

In [61]:
np.max(arr, axis=1)

array([3, 6, 9])

In [62]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [63]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [64]:
x = 10
y = 40

In [65]:
np.maximum(x, y)

40

In [67]:
np.maximum(arr, np.random.randn(3, 3))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [68]:
np.mean(arr)

5.0

In [69]:
arr.mean()

5.0

In [71]:
np.argmin([8, 4, 6, 3, 7, 0, 6, 4, 8, 5])

5

In [72]:
np.argmax([8, 4, 6, 3, 7, 0, 6, 4, 8, 5])

0

In [74]:
data = np.random.randn(3, 3)
data

array([[ 0.23224845, -0.45460196, -0.07520463],
       [ 0.68726246, -0.27930024, -1.41230492],
       [-0.74933098, -1.33525685, -0.05248074]])

In [75]:
np.argmax(data)

3

In [76]:
data = np.random.randn(3, 3, 3)
np.argmax(data)

23

In [78]:
# np.where()    np.unique()

In [79]:
data

array([[[-1.22823122, -0.29487198,  0.03820292],
        [ 1.65911432, -0.33926299, -0.26105841],
        [-2.32598986, -0.73472773,  1.00787859]],

       [[-0.84565064,  0.12395116, -0.63878074],
        [ 0.0415661 , -0.95534315,  0.66513028],
        [-2.51754303,  1.2526999 ,  0.50516848]],

       [[ 0.72770898,  0.37953243,  0.65723216],
        [ 1.37627515, -0.28939585,  2.8265142 ],
        [ 1.21801742,  0.79844653,  1.10541735]]])

In [84]:
data_w = np.where(data > 0, 5, 0)
data_w

array([[[0, 0, 5],
        [5, 0, 0],
        [0, 0, 5]],

       [[0, 5, 0],
        [5, 0, 5],
        [0, 5, 5]],

       [[5, 5, 5],
        [5, 0, 5],
        [5, 5, 5]]])

In [85]:
np.unique(data_w)

array([0, 5])

In [86]:
np.unique(data_w, return_counts=True)

(array([0, 5]), array([11, 16], dtype=int64))