# Numpy Basic

In [ ]:
import numpy as np

## data type

array의 dtype을 본다. 

In [ ]:
arr = np.array([[1., 2, 3], [1, 2, 3]])

In [ ]:
arr.dtype

.astype()으로 datatype을 변환 가능

In [ ]:
arr = arr.astype(np.int32)
arr

In [ ]:
arr = np.array([[1., 2, 3], [1, 2, 3]], dtype=np.uint8)
arr.dtype

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [ ]:
len(arr.shape)

In [ ]:
arr.shape

size 확인

In [ ]:
arr.size

dtype 확인

In [ ]:
arr.dtype

## Reshape

In [ ]:
arr.shape

Reshape 

In [ ]:
arr = arr.reshape([1, 6])
arr.shape

In [ ]:
arr = np.array([[1, 2, 3], [1, 2, 3]])

In [ ]:
arr.reshape([6]).shape

Reshape, -1 활용

In [ ]:
arr = arr.reshape(-1)
arr.shape

In [ ]:
arr = arr.reshape(-1, 3)
arr.shape

random array 생성

In [ ]:
arr = np.random.randn(8, 8)
arr.shape

In [ ]:
arr = arr.reshape([32, 2])
arr.shape

3차원으로 늘리기

In [ ]:
arr = arr.reshape(-1, 2, 1, 1, 1, 1)
arr.shape

In [ ]:
arr

## Ravel

In [ ]:
arr.shape

In [ ]:
arr = arr.ravel()
arr.shape

arr의 차원을 1로 바꿔줌  
나중에 배울 layer를 flatten 할 때 같은 기능이라 생각하면 됨 

arr.reshape(-1) 와 같음

In [ ]:
arr.ravel() == arr.reshape(-1)

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

In [ ]:
arr.shape

In [ ]:
arr = np.expand_dims(arr, -1)
arr.shape

In [ ]:
arr = arr.ravel()

In [ ]:
arr.shape

In [ ]:
arr = np.expand_dims(np.expand_dims(arr, -1), 0)

In [ ]:
arr.shape

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [ ]:
zeros = np.zeros([3, 3])
zeros

In [ ]:
zeros = np.zeros(1)
zeros

In [ ]:
ones = np.ones([10, 5])
ones

In [ ]:
ones * 5

In [ ]:
arr = np.arange(5)
arr

In [ ]:
arr = np.arange(4, 9)
arr

In [ ]:
arr = np.arange(10, 20)
arr

In [ ]:
arr = np.arange(9).reshape(3, 3)
arr

# Index

In [ ]:
nums = [1, 2, 3, 4, 5]

In [ ]:
nums[2:]

In [ ]:
nums = [1, 2, 3, 4, [1, 2, 3]]
nums

In [ ]:
nums[4]

In [ ]:
arr[1][2]

In [ ]:
arr[1, 2]

# Slicing

In [ ]:
arr

In [ ]:
arr[1:]

In [ ]:
arr[1:, 1:]

In [ ]:
arr

## Boolean Indexing

In [ ]:
data = np.random.randn(3, 3)
data

In [ ]:
data <= 0

In [ ]:
data[data <= 0] = 1

In [ ]:
data

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [2]:
import numpy as np

In [3]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [7]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr + np.array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## Math Function

In [10]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [11]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [12]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [13]:
np.add(arr, 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [16]:
arr = np.random.randint(2, size=27).reshape(3, 3, 3)
arr_2 = np.random.randint(2, size=9).reshape(3, 3)

In [21]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [22]:
arr + arr_2

array([[[0, 1, 1],
        [0, 1, 0],
        [1, 1, 1]],

       [[0, 1, 1],
        [1, 2, 0],
        [1, 0, 1]],

       [[1, 0, 0],
        [0, 2, 1],
        [1, 1, 2]]])

In [23]:
arr * arr_2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])

In [25]:
np.sum(arr)

12

In [26]:
np.sum(arr + arr_2)

21

In [29]:
arr + arr_2

array([[[0, 1, 1],
        [0, 1, 0],
        [1, 1, 1]],

       [[0, 1, 1],
        [1, 2, 0],
        [1, 0, 1]],

       [[1, 0, 0],
        [0, 2, 1],
        [1, 1, 2]]])

In [28]:
np.max(arr + arr_2)

2

In [30]:
np.min(arr + arr_2)

0

In [34]:
np.max(arr + arr_2, -1)

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 2]])

In [36]:
arr + arr_2

array([[[0, 1, 1],
        [0, 1, 0],
        [1, 1, 1]],

       [[0, 1, 1],
        [1, 2, 0],
        [1, 0, 1]],

       [[1, 0, 0],
        [0, 2, 1],
        [1, 1, 2]]])

In [38]:
np.sum(arr + arr_2, axis=-1)

array([[2, 1, 3],
       [2, 3, 2],
       [1, 3, 4]])

In [39]:
np.mean(arr)

0.4444444444444444

In [44]:
arr = np.array([1, 6, 3, 7, 3, 2, 9, 0, 2])
arr

array([1, 6, 3, 7, 3, 2, 9, 0, 2])

In [45]:
np.argmax(arr)

6

In [46]:
np.argmin(arr)

7

In [47]:
arr = np.array([3, 5, 6, 6, 3, 3, 1])

In [48]:
np.unique(arr)

array([1, 3, 5, 6])